name: "Terraform CI/CD"

# Trigger when a pull request is received
on: [pull_request]
jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
      - name: "Terraform Plan"
        run: |
          make plan
      # Provides AWS credentials to Terraform
      # By default, Terraform checks the home directory for a .aws folder with a credential file
      # Documentation: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/create-shared-credentials-file.html
      #- name: "Setup - Build AWS Credentials"
        #run: |
         # mkdir -p ~/.aws
          #echo "[default]" > ~/.aws/credentials
          #echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          #echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
                
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
          
      
         
        #Init pulls credentials from the .aws/credentials file by default
      - name: "Run - Terraform Init"
        uses: hashicorp/setup-terraform@v1.0.1

      - name: "Terraform Init"
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo '${{ secrets.SSH_PRIVATE_KEY }}' >> ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          echo "github.com ssh-rsa ${{ env.GITHUB_COM_SSH_RSA_PUBLIC_KEY }}" >> ~/.ssh/known_hosts
          chmod 400 ~/.ssh/known_hosts
          cd terraform
          terraform init  -input=false
      
      # The id value is used for reference in the comment step via "steps.plan.outputs.stdout"
      # Note: Color is disabled to prevent messy characters from appearing in the pull request comment
      - name: "Run - Terraform Plan"
        id: plan
        run: |
          cd terraform
          terraform plan -var-file="terraform.tfvars" -input=false -no-color
           
      # Submit a comment with the plan output to the pull request
      - name: "Run - Terraform Comment"
        uses: actions/github-script@0.9.0
        env:
          STDOUT: "```${{ steps.plan.outputs.stdout }}```"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.STDOUT
            })