name: "Terraform CI/CD"

# Trigger when a pull request is received
on: [pull_request]
jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
      - name: "Terraform Plan"
        run: |
         make plan